version: 2
updates:
  - package-ecosystem: "gradle"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
    reviewers:
      - "huebner-j"
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "huebner-j"