version: 2
updates:
  - package-ecosystem: "gradle"
    target_branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
    reviewers:
      - "huebner-j"
  - package-ecosystem: "github-actions"
    target_branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"
      prefix_development: "chore"
      include_scope: true
    reviewers:
      - "huebner-j"